# This file was generated by GoReleaser. DO NOT EDIT.
cask "agentrule" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "9883da85c5d14b0663272aba757e6119efd74c15d4e1763d90e0cb6374aa492f"
      url "https://github.com/mewisme/agentrule/releases/download/v#{version}/agentrule_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "6022c5c88f8074ad996a7d7152b5cea20aa11a5f65a361dd2d0a87c4dcc7238d"
      url "https://github.com/mewisme/agentrule/releases/download/v#{version}/agentrule_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "6e434650e0c83c3a0c7fba38ce8e5bfa3a0748bdf9a3857883a76d77fbe593e5"
      url "https://github.com/mewisme/agentrule/releases/download/v#{version}/agentrule_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "756ae380f4b1700742606b2296cc6a7b51ef11942e1bedd514a0acf9b5224f1a"
      url "https://github.com/mewisme/agentrule/releases/download/v#{version}/agentrule_#{version}_linux_arm64.tar.gz"
    end
  end

  name "agentrule"
  desc "CLI to install agent instruction rules across Cursor, Claude, Codex, and more"
  homepage "https://github.com/mewisme/agentrule"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "agentrule"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/agentrule"]
    end
  end

  # No zap stanza required

end
