# This file was generated by GoReleaser. DO NOT EDIT.
cask "agentrule" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "8d9d0bedc4b60f10a27b1253cd6dc09488a6a9f187795442ca2f86ed6f5b3407"
      url "https://github.com/mewisme/agentrule/releases/download/v#{version}/agentrule_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "fbf3fa0a27cb555ef689063deb9db280418984696b1af716fb2427b86d577d8b"
      url "https://github.com/mewisme/agentrule/releases/download/v#{version}/agentrule_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "5e73476b04085873f7dc4c229c65b8fbcca8529a2fd2dd9ee32dcc6455659597"
      url "https://github.com/mewisme/agentrule/releases/download/v#{version}/agentrule_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "1a2286e44330934522a57de3f0b775bb7313874de418d53ce6e0b146cd15bb2a"
      url "https://github.com/mewisme/agentrule/releases/download/v#{version}/agentrule_#{version}_linux_arm64.tar.gz"
    end
  end

  name "agentrule"
  desc "CLI to install agent instruction rules across Cursor, Claude, Codex, and more"
  homepage "https://github.com/mewisme/agentrule"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "agentrule"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/agentrule"]
    end
  end

  # No zap stanza required

end
