# This file was generated by GoReleaser. DO NOT EDIT.
cask "agentrule" do
  version "0.1.3"

  on_macos do
    on_intel do
      sha256 "bc6b0dfaf0e525cfcf7aa35d67b58a602cba3061f46f58fb5f16ed5a31eb721e"
      url "https://github.com/mewisme/agentrule/releases/download/v#{version}/agentrule_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "9dba700731cd00312a37a42d2eb7ae1ddf25cb4a342b09b876e0d972a35cebdd"
      url "https://github.com/mewisme/agentrule/releases/download/v#{version}/agentrule_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "9aabb52543cd9aeb9660ad312689aeb0152a4bda3d6d7071fd8f205badcb2bbf"
      url "https://github.com/mewisme/agentrule/releases/download/v#{version}/agentrule_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "2704a4f557dc58f3613404848a0840e2a5ec02b54cbfe11e5e9e96b514624b68"
      url "https://github.com/mewisme/agentrule/releases/download/v#{version}/agentrule_#{version}_linux_arm64.tar.gz"
    end
  end

  name "agentrule"
  desc "CLI to install agent instruction rules across Cursor, Claude, Codex, and more"
  homepage "https://github.com/mewisme/agentrule"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "agentrule"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/agentrule"]
    end
  end

  # No zap stanza required

end
