# This file was generated by GoReleaser. DO NOT EDIT.
cask "chatgpt-mcp" do
  version "0.2.3"

  on_macos do
    on_arm do
      sha256 "d5eb3661d32584ad1eb814a5b83d0e2b2b62c591377894d5bd5823e520141a68"
      url "https://github.com/mewisme/chatgpt-mcp/releases/download/v#{version}/chatgpt-mcp_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "bef735ef2f4e5f9dcf12ee7deefe24f961741c3e29f68387e96564804c5e293f"
      url "https://github.com/mewisme/chatgpt-mcp/releases/download/v#{version}/chatgpt-mcp_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "148fc80ed1388a64a0aa299ec58705672324f71777f006aca344acf1207e6510"
      url "https://github.com/mewisme/chatgpt-mcp/releases/download/v#{version}/chatgpt-mcp_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "45c2673444d38439d179085c7c5627a80666a25f4c52856695e85a474a33590d"
      url "https://github.com/mewisme/chatgpt-mcp/releases/download/v#{version}/chatgpt-mcp_#{version}_linux_amd64.tar.gz"
    end
  end

  name "chatgpt-mcp"
  desc "Self-hosted MCP 2026-07-28 runtime with local tools, upstream MCP aggregation, and OpenAI tunnel support"
  homepage "https://github.com/mewisme/chatgpt-mcp"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "chatgpt-mcp"


  binary "chatgpt-mcp", target: "cgm"
  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/chatgpt-mcp"]
    end
  end

  # No zap stanza required
end
