# This file was generated by GoReleaser. DO NOT EDIT.
cask "chatgpt-mcp" do
  version "0.2.12"

  on_macos do
    on_arm do
      sha256 "cef4be90c5457fdad8aab2462cd56ba31e05b671783d11079bc5c11bb4bb3cbc"
      url "https://github.com/mewisme/chatgpt-mcp/releases/download/v#{version}/chatgpt-mcp_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "5842c0c0735f9b7f1bd30c156f89ef8f8985477d1ca676c4c61a434796d23ce2"
      url "https://github.com/mewisme/chatgpt-mcp/releases/download/v#{version}/chatgpt-mcp_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "4f4b7f274ed28b1b61604394c35952182bca8ac1ddebe2bdc763565bfd866a8d"
      url "https://github.com/mewisme/chatgpt-mcp/releases/download/v#{version}/chatgpt-mcp_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "e34b1e49060b9043ea75ffb416faa25727374f6522c231b38ba89c1092c43e0b"
      url "https://github.com/mewisme/chatgpt-mcp/releases/download/v#{version}/chatgpt-mcp_#{version}_linux_amd64.tar.gz"
    end
  end

  name "chatgpt-mcp"
  desc "Self-hosted MCP 2026-07-28 runtime with local tools, upstream MCP aggregation, and OpenAI tunnel support"
  homepage "https://github.com/mewisme/chatgpt-mcp"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "chatgpt-mcp"


  binary "chatgpt-mcp", target: "cgm"
  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/chatgpt-mcp"]
    end
  end

  # No zap stanza required
end
