# This file was generated by GoReleaser. DO NOT EDIT.
cask "chatgpt-mcp" do
  version "0.2.17"

  on_macos do
    on_arm do
      sha256 "b8dee64b69d8d123727cfe95c958a4e2fb19955772533c308d4bea901d97dd3d"
      url "https://github.com/mewisme/chatgpt-mcp/releases/download/v#{version}/chatgpt-mcp_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "f859cd116bf465d5cb9391b47927f240e62da31ab35947a0732e9e37a8408472"
      url "https://github.com/mewisme/chatgpt-mcp/releases/download/v#{version}/chatgpt-mcp_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "e1cc5ef6a700e72809289aa66bf175b1fdf076ff024d1c7810fad3401a5f6231"
      url "https://github.com/mewisme/chatgpt-mcp/releases/download/v#{version}/chatgpt-mcp_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "d876c5849aaa533c4d7004862068ee9a8317c21a7f8c9953474aa799241699c6"
      url "https://github.com/mewisme/chatgpt-mcp/releases/download/v#{version}/chatgpt-mcp_#{version}_linux_amd64.tar.gz"
    end
  end

  name "chatgpt-mcp"
  desc "Self-hosted MCP 2026-07-28 runtime with local tools, upstream MCP aggregation, and OpenAI tunnel support"
  homepage "https://github.com/mewisme/chatgpt-mcp"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "chatgpt-mcp"


  binary "chatgpt-mcp", target: "cgm"
  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/chatgpt-mcp"]
    end
  end

  # No zap stanza required
end
