# This file was generated by GoReleaser. DO NOT EDIT.
cask "codemcp" do
  version "0.3.2"

  on_macos do
    on_intel do
      sha256 "b7f01494e8ff3bc5a83c3ed4b4361ea26e0567857c4d62de65b8323bc1678f93"
      url "https://github.com/mewisme/codemcp/releases/download/v#{version}/codemcp_darwin_amd64.tar.gz"
    end
    on_arm do
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the codemcp
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end
  on_linux do
    on_arm do
      sha256 "5c1ceee0a6cf03e597e74d42c858a676ca85fa46db5e61a2164d254a7ecd98d1"
      url "https://github.com/mewisme/codemcp/releases/download/v#{version}/codemcp_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "7006cb88436b1666323fcf1e58b01943710960fd94c2a6a919fa6b890b8f4083"
      url "https://github.com/mewisme/codemcp/releases/download/v#{version}/codemcp_linux_amd64.tar.gz"
    end
  end

  name "codemcp"
  desc "A secure, workspace-bound MCP bridge connecting ChatGPT, Claude, and other AI agents to your machine."
  homepage "https://github.com/mewisme/codemcp"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cm"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cm"]
    end
  end

  # No zap stanza required
end
