# This file was generated by GoReleaser. DO NOT EDIT.
cask "codemcp" do
  version "0.3.1"

  on_macos do
    on_intel do
      sha256 "37758f1bedafe304388a72208ee33c28c9338157ecc4e0caf79565ea7966d1bf"
      url "https://github.com/mewisme/codemcp/releases/download/v#{version}/codemcp_darwin_amd64.tar.gz"
    end
    on_arm do
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the codemcp
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end
  on_linux do
    on_arm do
      sha256 "f894700e8ff597e17c568b85f3ad6e672df4cba420d240ab16b9692c9ef4a460"
      url "https://github.com/mewisme/codemcp/releases/download/v#{version}/codemcp_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "f34ce9d31f22a8b9b8dd7d360dcadf42de85ce6b1e5f8d5918cb2f2c5c0949e7"
      url "https://github.com/mewisme/codemcp/releases/download/v#{version}/codemcp_linux_amd64.tar.gz"
    end
  end

  name "codemcp"
  desc "A secure, workspace-bound MCP bridge connecting ChatGPT, Claude, and other AI agents to your machine."
  homepage "https://github.com/mewisme/codemcp"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cm"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cm"]
    end
  end

  # No zap stanza required
end
