# This file was generated by GoReleaser. DO NOT EDIT.
cask "codemcp" do
  version "0.3.1"

  on_macos do
    on_intel do
      sha256 "984ae79acca15a7a4e46caa5a119326e34dabeb56470cac831306f27fb3ba8fd"
      url "https://github.com/mewisme/codemcp/releases/download/v#{version}/codemcp_darwin_amd64.tar.gz"
    end
    on_arm do
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the codemcp
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end
  on_linux do
    on_arm do
      sha256 "f80b00c7c126191c43887dbf7e1304b30268c20bb57901a24252d54cbc4cada3"
      url "https://github.com/mewisme/codemcp/releases/download/v#{version}/codemcp_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "5c5d68fea5c5372b4aec4fa2852f70fce7f28ab697baee2b3e67449944f23fbf"
      url "https://github.com/mewisme/codemcp/releases/download/v#{version}/codemcp_linux_amd64.tar.gz"
    end
  end

  name "codemcp"
  desc "A secure, workspace-bound MCP bridge connecting ChatGPT, Claude, and other AI agents to your machine."
  homepage "https://github.com/mewisme/codemcp"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cm"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cm"]
    end
  end

  # No zap stanza required
end
