# This file was generated by GoReleaser. DO NOT EDIT.
cask "discloud-cli" do
  version "0.1.12"

  on_macos do
    on_intel do
      sha256 "1bfdaede453c0d17da34773ccafb245b8a438cfdb0ec7467cf4fe88c1b934738"
      url "https://github.com/mewisme/discloud-go/releases/download/v#{version}/discloud-cli_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "d0031f44f25df91089f8c77d2e0ac4baeaf5482f22e02419b7193167aec78d91"
      url "https://github.com/mewisme/discloud-go/releases/download/v#{version}/discloud-cli_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "4c9721db082fe381a26ca87f9a1db3f76fa78dfc64b80c680e96d3abc3f0e283"
      url "https://github.com/mewisme/discloud-go/releases/download/v#{version}/discloud-cli_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "77e29f0be5a2d84931b680b56f797b1dab18b255131d5700c435e5ebd130d597"
      url "https://github.com/mewisme/discloud-go/releases/download/v#{version}/discloud-cli_#{version}_linux_arm64.tar.gz"
    end
  end

  name "discloud-cli"
  desc "CLI client for DisCloud (Discord-backed file storage)"
  homepage "https://github.com/mewisme/discloud-go"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "discloud-cli"

  postflight do
    FileUtils.ln_sf "#{staged_path}/discloud-cli", "#{staged_path}/discloud"
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/discloud-cli"]
    end
  end
  generate_completions_from_executable "discloud-cli",
    base_name: "discloud",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish]

  # No zap stanza required

end
