# This file was generated by GoReleaser. DO NOT EDIT.
cask "discloud-cli" do
  version "0.1.6"

  on_macos do
    on_intel do
      sha256 "8052123e326d727c495f4dfe76062512d6d26c0f086b50844142bd9d4481797a"
      url "https://github.com/mewisme/discloud-go/releases/download/v#{version}/discloud-cli_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "51f5a050a3bee7c00382691be2fa3fb807268f08d76d70740f73d8b08085f004"
      url "https://github.com/mewisme/discloud-go/releases/download/v#{version}/discloud-cli_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "4044c5baaf95ccea10a7c6e331aed47ac4ae47653fa39b49025582c725038442"
      url "https://github.com/mewisme/discloud-go/releases/download/v#{version}/discloud-cli_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "cfb13ce62d51fb933573ae84944e9d1d613ac2feba15e6870a231ac621b5c7cc"
      url "https://github.com/mewisme/discloud-go/releases/download/v#{version}/discloud-cli_#{version}_linux_arm64.tar.gz"
    end
  end

  name "discloud-cli"
  desc "CLI client for DisCloud (Discord-backed file storage)"
  homepage "https://github.com/mewisme/discloud-go"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "discloud-cli"

  postflight do
    FileUtils.ln_sf "#{staged_path}/discloud-cli", "#{staged_path}/discloud"
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/discloud-cli"]
    end
  end
  generate_completions_from_executable "discloud-cli",
    base_name: "discloud",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish]

  # No zap stanza required

end
