# This file was generated by GoReleaser. DO NOT EDIT.
cask "discloud-cli" do
  version "0.3.1"

  on_macos do
    on_intel do
      sha256 "c916dba1b6f89c574c72635e4784a41ef8534d4f61944e3cb2f5178422536395"
      url "https://github.com/mewisme/discloud-go/releases/download/v#{version}/discloud-cli_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "40a8adeba26ef1078654d43d332ee91fe5da32f72a166bb792acfd620b219072"
      url "https://github.com/mewisme/discloud-go/releases/download/v#{version}/discloud-cli_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d9f638ad6c45b8d0bd8fabbc2b139e620517e3115e3262dfd14a6ee59d89b183"
      url "https://github.com/mewisme/discloud-go/releases/download/v#{version}/discloud-cli_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "c42d0762e6647180ce6b44fde3cc5074f76fef7b9636533fce2612b6ebfc4fbc"
      url "https://github.com/mewisme/discloud-go/releases/download/v#{version}/discloud-cli_#{version}_linux_arm64.tar.gz"
    end
  end

  name "discloud-cli"
  desc "CLI client for DisCloud (Discord-backed file storage)"
  homepage "https://github.com/mewisme/discloud-go"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "discloud-cli"

  postflight do
    FileUtils.ln_sf "#{staged_path}/discloud-cli", "#{staged_path}/discloud"
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/discloud-cli"]
    end
  end
  generate_completions_from_executable "discloud-cli",
    base_name: "discloud",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish]

  # No zap stanza required

end
