# This file was generated by GoReleaser. DO NOT EDIT.
cask "initrule" do
  version "0.0.11"

  on_macos do
    on_intel do
      sha256 "174f03b6f06726fe4ec9c6a4fb084d7dccedb4073bc387e448a21aec5e7516af"
      url "https://github.com/mewisme/initrule/releases/download/v#{version}/initrule_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "4563c35b19a7d95fdd2acbd50c46899690af4d192af13182ac0430ce92cb169c"
      url "https://github.com/mewisme/initrule/releases/download/v#{version}/initrule_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "1da9920ebb9bbd6d90ee811e36ec1c68debf01695bb521b4a081417e94f67d09"
      url "https://github.com/mewisme/initrule/releases/download/v#{version}/initrule_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "6b8571c2090dba0b4d9a119d6c22cf9ce1ed1266dacba69a817849d045905fbe"
      url "https://github.com/mewisme/initrule/releases/download/v#{version}/initrule_#{version}_linux_arm64.tar.gz"
    end
  end

  name "initrule"
  desc "CLI to install Cursor rule files (.cursor/rules/*.mdc) into a project"
  homepage "https://github.com/mewisme/initrule"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "initrule"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/initrule"]
    end
  end

  # No zap stanza required

end
