# This file was generated by GoReleaser. DO NOT EDIT.
cask "initrule" do
  version "0.0.10"

  on_macos do
    on_intel do
      sha256 "1af0688a373cf8e6cde4dc62231eb98f7f3ae67b3469dabd67403066dd083c31"
      url "https://github.com/mewisme/initrule/releases/download/v#{version}/initrule_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "652dd7717577995ad1b1372673e00a8d63cc0b8e785d5564995f20954424396d"
      url "https://github.com/mewisme/initrule/releases/download/v#{version}/initrule_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "4c0361d1afbe7587e236ff129a54269630afe8301b0d9cf16f2765865ecaa081"
      url "https://github.com/mewisme/initrule/releases/download/v#{version}/initrule_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "1d6684bcbce18229c7fe36cc07445471a5d7b16e0f42f926e1068d58ef4561a3"
      url "https://github.com/mewisme/initrule/releases/download/v#{version}/initrule_#{version}_linux_arm64.tar.gz"
    end
  end

  name "initrule"
  desc "CLI to install Cursor rule files (.cursor/rules/*.mdc) into a project"
  homepage "https://github.com/mewisme/initrule"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "initrule"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/initrule"]
    end
  end

  # No zap stanza required

end
