# This file was generated by GoReleaser. DO NOT EDIT.
cask "initrule" do
  version "0.0.14"

  on_macos do
    on_intel do
      sha256 "293c3e0373c92f9913c77d2bd1ee0d5383a93b6a9e6d674392d1ffdf4607552e"
      url "https://github.com/mewisme/initrule/releases/download/v#{version}/initrule_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "7871c836da58a4baf5c4c60017679f11fa80cf8a0c90984d236eabd90db7ecb1"
      url "https://github.com/mewisme/initrule/releases/download/v#{version}/initrule_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "6e5ffffe61be0a3ca247510be2389029ac0d532bf989d577b7a00443b1d3ca70"
      url "https://github.com/mewisme/initrule/releases/download/v#{version}/initrule_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "7658fad7afcfbd1afc1310a8a187add223b3820eb4a924aaf617627b14b769bb"
      url "https://github.com/mewisme/initrule/releases/download/v#{version}/initrule_#{version}_linux_arm64.tar.gz"
    end
  end

  name "initrule"
  desc "CLI to install Cursor rule files (.cursor/rules/*.mdc) into a project"
  homepage "https://github.com/mewisme/initrule"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "initrule"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/initrule"]
    end
  end

  # No zap stanza required

end
